// Task6-WebComponents/react/src/App/App.jsx
import React from 'react';

import Hello from '../Hello';
import '../customElements/x-spinner';
import './app.less';

class App extends React.Component {

    show() {
        var spinners = document.querySelectorAll('x-spinner');
        [].forEach.call(spinners, spinner => spinner.show());
    }

    hide() {
        var spinners = document.querySelectorAll('x-spinner');
        [].forEach.call(spinners, spinner => spinner.hide());
    }

    render() {
        return (
            <div>
                <button onClick={this.show}>show</button>
                <button onClick={this.hide}>hide</button>

                <div className="block block1">
                    <Hello name="World" />
                    <Hello name="World" />
                    <Hello name="World" />
                    <Hello name="World" />
                    <Hello name="World" />
                    <x-spinner></x-spinner>
                </div>

                <div className="block block2">
                    <Hello name="friend" />
                    <x-spinner></x-spinner>
                </div>

                <div className="block block3">
                    <Hello name="Denis" />
                    <x-spinner></x-spinner>
                </div>
            </div>
        );
    }
}

export default App;

// Task6-WebComponents/angular2/src/app/app.js
import { Component } from '@angular/core';

import '../customElements/x-spinner';
import './app.less';

@Component({
    selector: 'my-app',
    template: `
        <div>
            <button (click)="show()">show</button>
            <button (click)="hide()">hide</button>

            <div class="block block1">
                <x-spinner></x-spinner>
            </div>

            <div class="block block2">
                <x-spinner></x-spinner>
            </div>

            <div class="block block3">
                <x-spinner></x-spinner>
            </div>
        </div>
    `
})
export default class App {

    show() {
        var spinners = document.querySelectorAll('x-spinner');
        [].forEach.call(spinners, spinner => spinner.show());
    }

    hide() {
        var spinners = document.querySelectorAll('x-spinner');
        [].forEach.call(spinners, spinner => spinner.hide());
    }
};
